name: 🛠️ 编译固件

on:
  workflow_dispatch:
    inputs:
      device:
        description: '⚙️ 请选择要编译的目标设备型号'
        required: true
        default: 'ruijie_rg-x60-new'
        type: choice
        options:
          - 'abt_asr3000'
          - 'cetron_ct3003'
          - 'cmcc_a10'
          - 'cmcc_a10-256m'
          - 'cudy_tr3000-v1'
          - 'cudy_tr3000-v1-256mb'
          - 'glinet_gl-mt3000'
          - 'glinet_gl-mt6000'
          - 'jdcloud_re-cp-03'
          - 'netcore_n60-pro'
          - 'netcore_n60-pro-512rom'
          - 'nokia_ea0326gmp'
          - 'philips_hy3000'
          - 'qihoo_360t7'
          - 'ruijie_ew-6000gx-pro'          
          - 'ruijie_rg-x60-new'
          - 'ruijie_rg-x60-pro'
          - 'sl_3000-emmc'
          - 'sn_r1'
          - 'supergateway_s20l'
          - 'supergateway_s20m'
          - 'supergateway_s20p'
      wifi_ssid:
        description: '📶 设置默认无线网络（WiFi）名称（SSID）'
        required: true
        default: 'ZeroWrt'
        type: string
      wifi_password:
        description: '🔐 设置默认无线网络（WiFi）密码（可选，留空则为开放网络）'
        required: false
        default: ''
        type: string
      lan_addr:
        description: '📍 设置固件默认局域网（LAN）IP 地址（可选，留空则为 10.0.0.1 ）'
        required: false
        default: ''
        type: string
      root_password:
        description: '🛡️ 设置后台（root）默认密码（可选，留空则无密码）'
        required: false
        default: ''
        type: string
      build_uboot:
        description: '🧩 是否同时编译 U-Boot（可选）'
        type: boolean
        default: false

jobs:
  Build_Firmware:
    runs-on: ubuntu-24.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}
    permissions:
      contents: write

    env:
      REPO_URL: https://github.com/Yuzhii0718/immortalwrt-mt798x-6.6-padavanonly
      REPO_BRANCH: openwrt-24.10-6.6
      CONFIG_FILE: configs/${{ github.event.inputs.device }}.config
      PREPARE_BASE_SH: scripts/00-prepare_base.sh
      PREPARE_PACKAGE_SH: scripts/01-prepare_package.sh
      WIFI_SSID: ${{ github.event.inputs.wifi_ssid }}
      WIFI_PASSWORD: ${{ github.event.inputs.wifi_password }}
      LAN_ADDR: ${{ github.event.inputs.lan_addr }}
      ROOT_PASSWORD: ${{ github.event.inputs.root_password }}
      CACHE_TOOLCHAIN: true
      TZ: Etc/UTC
      
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check Server Performance
        run: |
          echo -e "\n\033[1;36m==================== System Info ====================\033[0m"
          echo -e "\n\033[1;32m[ CPU ]\033[0m"
          CPU_NAME=$(grep -m1 'model name' /proc/cpuinfo | awk -F ': ' '{print $2}')
          CPU_MHZ=$(grep -m1 'cpu MHz' /proc/cpuinfo | awk -F ': ' '{print $2}')
          CPU_CORES=$(grep -c 'processor' /proc/cpuinfo)
          echo -e "  Model : $CPU_NAME"
          echo -e "  Speed : ${CPU_MHZ} MHz"
          echo -e "  Cores : ${CPU_CORES}"
          echo -e "\n\033[1;32m[ Memory ]\033[0m"
          free -h | awk 'NR==1 || NR==2 || NR==3 {print "  " $0}'
          echo -e "\n\033[1;32m[ Storage ]\033[0m"
          df -Th / /mnt 2>/dev/null | awk '{print "  " $0}'
          echo -e "\n\033[1;32m[ System ]\033[0m"
          lsb_release -a 2>/dev/null | sed 's/^/  /'
          echo -e "\n\033[1;32m[ Kernel ]\033[0m"
          uname -a | sed 's/^/  /'
          echo -e "\n\033[1;36m=====================================================\033[0m"
        
      - name: Initialize the build environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi -f $(docker images -q) 2>/dev/null || true
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2404-make-openwrt-depends)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          sudo -E timedatectl set-timezone "${TZ:-Etc/UTC}"
          sudo -E ntpdate ntp.ubuntu.com 0.pool.ntp.org || true
          sudo -E timedatectl set-ntp true
          date -u
          timedatectl status || true
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Create virtual disk for extended storage
        id: disk
        run: |
          # Get available space in exact GB
          root_avail=$(df --block-size=1G / | tail -1 | awk '{print $4}')
          root_size=$(( root_avail - 4 ))
          [[ "${root_size}" -gt 0 ]] || { echo "Error: Insufficient space on /: ${root_avail}G available"; exit 1; }

          sudo truncate -s "${root_size}"G /root.img
          build_dev=$(sudo losetup --find --show /root.img)
          echo "Using /: ${root_size}G"

          sudo mkfs.xfs -f -i sparse=0 -b size=4096 "${build_dev}"
          sudo mkdir -p /builder
          sudo mount "${build_dev}" /builder
          sudo chown -R runner:runner /builder
          df -Th
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Clone source code
        id: codes
        working-directory: /builder
        run: |
          git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
          ln -sf /builder/openwrt ${{ github.workspace }}/openwrt

      - name: Cache Toolchain
        if: env.CACHE_TOOLCHAIN == 'true'
        uses: HiGarfield/cachewrtbuild@main
        with:
          ccache: false
          mixkey: immortalwrt-mt798x-${{ env.REPO_BRANCH }}
          prefix: /builder/openwrt
        
      - name: Update feeds
        run: cd openwrt/ && ./scripts/feeds update -a

      - name: Install feeds
        run: cd openwrt/ && ./scripts/feeds install -a

      - name: Load prepare base script
        run: |
          chmod +x ${PREPARE_BASE_SH}
          cd openwrt/
          ${{ github.workspace }}/${PREPARE_BASE_SH}

      - name: Load prepare package script
        run: |
          [[ -d "files" ]] && mv -f files openwrt/files
          [[ -e "${CONFIG_FILE}" ]] && cp -f ${CONFIG_FILE} openwrt/.config
          chmod +x ${PREPARE_PACKAGE_SH}
          cd openwrt/
          ${{ github.workspace }}/${PREPARE_PACKAGE_SH}

      - name: Download package
        id: package
        run: |
          cd openwrt/
          make defconfig
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Get OpenWrt source commit hash
        id: openwrthash
        run: |
          # Get the latest source hash from the kernel repository
          repo_path="$(echo "${{ env.REPO_URL }}" | awk -F"github.com/" '{print $2}')"
          api_url="https://api.github.com/repos/${repo_path}/git/ref/heads/${{ env.REPO_BRANCH }}"
          source_hash=$(curl -fsSL -m 20 \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${api_url} |
              jq -r '.object.sha'
          )
          [[ -z "${source_hash}" || "${source_hash}" == "null" ]] && source_hash="${{ github.sha }}"
          echo "source_hash=${source_hash}" >> ${GITHUB_ENV}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Compile the OpenWrt firmware
        id: compile
        run: |
          cd openwrt/
          echo -e "Compiling with $(nproc) threads"
          make -j$(nproc) || make -j1 || make -j1 V=s

          echo "status=success" >> ${GITHUB_OUTPUT}
          
      - name: Clean up build files and reclaim disk space
        id: clean
        if: ${{ steps.compile.outputs.status == 'success' && !cancelled() }}
        run: |
          # Clean up build artifacts and reclaim disk space
          cd openwrt/
          [[ -d "output" ]] || mkdir output
          rm -rf bin/targets/*/*/packages
          cp -rf bin/targets/*/*/ output/
          df -hT ${PWD}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: ${{ github.event.inputs.device }}-firmware
          path: openwrt/output

  Build_Uboot:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id && github.event.inputs.build_uboot == 'true' }}
    permissions:
      contents: write

    env:
      BL_URL: https://github.com/Yuzhii0718/bl-mt798x-dhcpd
      BL_BRANCH: master
      TZ: Etc/UTC

    steps:
      - name: Initialize the build environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install gcc-aarch64-linux-gnu build-essential flex bison libssl-dev device-tree-compiler qemu-user-static python2.7 gcc-arm-linux-gnueabi nodejs npm
          sudo -E apt-get -qq install rename tar
          sudo timedatectl set-timezone "$TZ"

      - name: Clone source code          
        run: |
          git clone -q --single-branch --depth=1 --branch=${BL_BRANCH} ${BL_URL} uboot

      - name: Compile the Uboot
        id: compile
        run: |
          cd uboot
          make BOARD=${{ github.event.inputs.device }} VERSION=SP1 SIMG=1

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: ${{ github.event.inputs.device }}-uboot
          path: uboot/output
          
  release:
    name: Create Release
    needs: [Build_Firmware,Build_Uboot]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@main
        with:
          path: output

      - name: Create Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.device }}
          name: ${{ github.event.inputs.device }}
          files: output/**/*
